# Configuração do nProtectV2 - Código totalmente refeito, agora muito mais rápido.
# Precisa de suporte? Contate-me via discord: NickUltracraft#4550
Config:
    # Configure aqui os grupos para se logarem como staffer.
    # O nome do grupo deve estar identico no PermissionsEx
    # Coloque entre aspas a senha desejada para cada cargo..
    Grupos:
        Mod: "nprotect_mod"
        Admin: "nprotect_admin"
        Master: "nprotect.master"
    # Caso utilize uma versão muito antiga, altere este valor para false,
    # para evitar problemas com erros.
    UsarTitle: true
    # Loga automaticamente staffers que já se logaram com o mesmo ip anteriormente.
    AutoLogin: true
    # Tempo para um staffer se autenticar com o /loginstaff
    TempoLogar: 25
    # Lista de comandos permitidos antes de usar /loginstaff
    ComandosPermitidos:
    - "/loginstaff"
    - "/login"
    - "/logar"
    - "/register"
    - "/registrar"
    - "/captcha"
    - "/email"
    - "/twitter"
    - "/pin"
# Lista de todas as mensagens do plugin.
# Caso uma mensagem não exista, o valor desta mensagem será default.
Mensagens:
    argumentos_invalidos: "&cVocê deve usar: /loginstaff <sua senha>"
    nao_staffer: "&cVocê deve ser um staffer para executar este comando."
    ja_autenticado: "&cVocê já está autenticado como staffer."
    senha_incorreta: "&cA senha inserida está incorreta."
    demorou_logar: "&cVocê demorou muito para se autenticar como staffer"
    mudousenha_sucesso: "&aVocê alterou a sua senha com sucesso."
    loginstaff_title: "&e&lLOGIN STAFF"
    logou_subtitle: "&eVocê logou com sucesso!"
    logou_subtitle_session: "&eSessão continuada com sucesso"
    logou_chat: "&aVocê logou como staffer com sucesso."
    logar_subtitle: "Se autentique usando /loginstaff <senha>"
    logar_chat: "&ePara se autenticar como staffer, utilize /loginstaff <sua senha>\n&e&lDICA: &eVocê deve inserir a senha do grupo %grupo%"
