name: nProtect-REBUILT
author: NickUltracraft
version: 1.9
main: nickultracraft.protect.Main
website: https://nickuc.tk
commands:
    mudarsenhastaff:
        aliases: [/changepasswordstaff]
    loginstaff:
        aliases: [/ls]