name: nProtect
author: NickUltracraft
version: 2.0
main: nickultracraft.protect.Main
website: https://nickuc.tk
commands:
    mudarsenhastaff:
        aliases: [/changepasswordstaff]
    loginstaff:
        aliases: [/ls]