#          ___           _            _
#  _ __   / _ \_ __ ___ | |_ ___  ___| |_
# | '_ \ / /_)/ '__/ _ \| __/ _ \/ __| __|
# | | | / ___/| | | (_) | ||  __/ (__| |_
# |_| |_\/    |_|  \___/ \__\___|\___|\__|

# Configuração do nProtect v 3.0
# Precisa de suporte? Entre em nosso grupo do discord: https://www.nickuc.com/discord

Config:
    debug-mode: false
    # Configure aqui os grupos para se logarem como staffer.
    # O nome do grupo deve estar identico no seu plugin de permissões [PermissionsEx, LuckPerms ou GroupManager]
    # Coloque entre aspas a senha desejada para cada cargo.
    # Formato: 'Grupo: SuaSenha'
    Grupos:
        Mod: "loginstaff_mod"
        Admin: "loginstaff_admin"
        Master: "loginstaff_master"
    # Caso utilize uma versão muito antiga, altere este valor para false,
    # para evitar problemas com erros.
    UsarTitle: true
    # Um usuário não esta em nenhum grupo acima ou não utiliza nenhum plugin de permissões compativel e tem a permissão 'loginstaff.staffer',
    # terá que usar qual senha para se logar?
    SenhaDefault: "nprotect_default"
    # Loga automaticamente staffers que já se logaram com o mesmo ip anteriormente.
    AutoLogin: true
    # Tempo para um staffer se autenticar com o /loginstaff
    TempoLogar: 25
    # Lista de comandos permitidos antes de usar /loginstaff
    ComandosPermitidos:
    - "/loginstaff"
    - "/login"
    - "/logar"
    - "/register"
    - "/registrar"
    - "/captcha"
    - "/email"
    - "/twitter"
    - "/pin"
# Lista de todas as mensagens do plugin.
# Caso uma mensagem não exista, o valor desta mensagem será default.
Mensagens:
    argumentos_invalidos: "&cVocê deve usar: /loginstaff <sua senha>"
    nao_staffer: "&cVocê deve ser um staffer para executar este comando."
    ja_autenticado: "&cVocê já está autenticado como staffer."
    senha_incorreta: "&cA senha inserida está incorreta."
    demorou_logar: "&cVocê demorou muito para se autenticar como staffer"
    mudousenha_sucesso: "&aVocê alterou a sua senha com sucesso."
    loginstaff_title: "&e&lLOGIN STAFF"
    logou_subtitle: "&eVocê logou com sucesso!"
    logou_subtitle_session: "&eSessão continuada com sucesso"
    logou_chat: "&aVocê logou como staffer com sucesso."
    logar_subtitle: "Se autentique usando /loginstaff <senha>"
    logar_chat: "&ePara se autenticar como staffer, utilize /loginstaff <sua senha>\n&e&lDICA: &eVocê deve inserir a senha do grupo %grupo%"
    logar_chat2: "&ePara se autenticar como staffer, utilize /loginstaff <sua senha>\n&e&lDICA: &eVocê deve inserir a senha para os grupos default."
